-- Script de mise à jour de la base de données CRM

-- Supprimer la table existante si elle existe
DROP TABLE IF EXISTS prospects;

-- Créer la table prospects avec tous les nouveaux champs
CREATE TABLE prospects (
    id SERIAL PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    prenom VARCHAR(255),
    email VARCHAR(255),
    telephone VARCHAR(50),
    entreprise VARCHAR(255),
    role VARCHAR(255),
    ville VARCHAR(100),
    statut VARCHAR(100) DEFAULT 'Prospect à contacter',
    linkedin TEXT,
    interets TEXT,
    historique TEXT,
    date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- Insérer quelques données de test avec les nouveaux champs
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            INSERT INTO prospects (nom, prenom, email, telephone, entreprise, role, ville, statut, linkedin, interets, historique) VALUES
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ('Dupont', 'Jean', 'jean.dupont@email.com', '0123456789', 'Entreprise A', 'Directeur Commercial', 'Luxembourg', 'Prospect à contacter', 'https://linkedin.com/in/jeandupont', 'Technologies, Innovation', 'Premier contact lors du salon Tech 2024'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ('Martin', 'Marie', 'marie.martin@email.com', '0987654321', 'Entreprise B', 'CEO', 'Genève', 'Client', 'https://linkedin.com/in/mariemartin', 'Management, Stratégie', 'Client depuis 2023, très satisfait de nos services'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ('Durand', 'Pierre', 'pierre.durand@email.com', '0555666777', 'Entreprise C', 'Développeur', 'Paris', 'Prospect à contacter', 'https://linkedin.com/in/pierredurand', 'Développement web, IA', 'À contacter cette semaine pour présenter nos solutions');

-- Afficher les données insérées
SELECT * FROM prospects; 